name: Linux

on:
  workflow_dispatch:
    inputs:
      flavors:
        description: "List of flavors to build"
        default: '["x86", "x86_64", "x86_64-musl", "armhf", "armel","armhf-musl", "armbe8", "arm64", "arm64be", "arm64beilp32", "arm64-musl", "mips", "mipsel", "mips64", "mips64el"]'

env:
  REGISTRY: ghcr.io

jobs:
  x-tools:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: ${{ fromJSON(github.event.inputs.flavors) }}
      fail-fast: false
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: x-tools
          file: x-tools/Dockerfile.linux-${{ matrix.flavor }}
          push: true
          tags: ghcr.io/runshine/x-tools-${{ matrix.flavor }}:latest

